Fix more issues with PHP 7
gregstoll/gallery2 pull request #3
Opened 2018-10-14 20:56 UTC by ctrueden

Thanks very much for this very helpful fork. I used it as a starting point to fix a Gallery2-based website when the webhost upgraded to PHP 7 and removed PHP 5. This PR includes commits that were necessary to get my Gallery upgraded and functioning again.

2018-10-15 00:57 UTC, gregstoll requested changes

2018-10-15 00:57 UTC, gregstoll commented on modules/comment/classes/GalleryCommentHelper.class
> +    static function  function &getAkismetSaveListenerSwitch(getAkismetSaveListenerSwitch() {
I'm not super familiar with PHP - are there supposed to be two "function"s in this line?

2018-10-15 00:58 UTC, gregstoll commented
Thanks so much for doing this!

2018-10-15 03:24 UTC, ctrueden commented on modules/comment/classes/GalleryCommentHelper.class
> +    static function  function &getAkismetSaveListenerSwitch(getAkismetSaveListenerSwitch() {
Good catch. This was a bug in the shell script I used to add the `static` keyword to functions annotated with `@static`. Fixed and force pushed now!

2018-10-16 01:47 UTC, gregstoll approved these changes

2018-10-16 01:48 UTC, merged