Core module unit testing
gregstoll/gallery2 pull request #95
Opened 2022-11-08 13:40 UTC by miceno

Some improvements to allow more robust refactoring:
* Docker image and docker compose
* unit testing for `core` module

2022-11-09 02:56 UTC, gregstoll commented
Thanks for this! Just FYI, it's going to take me at least a few days to review this.

2022-11-09 08:17 UTC, miceno commented
Sure! I suggest you first focus on the non-test changes, and give a try to the docker setup. Let me know if you find any issue.

2022-11-11 03:06 UTC, gregstoll requested changes
Looks good - just fix those two comments and I'll merge it!

2022-11-11 03:06 UTC, gregstoll commented on lib/tools/phpunit/CodeAuditTestCase.class
> +			$this->skip();
Does this need to be commented out as well? (like was done on line 43)

2022-11-11 03:06 UTC, gregstoll commented on modules/core/classes/GalleryUtilities.class
> -	    $value = (!is_null($value)) ? str_replace(array('&', '"', '<', '>'),
Can you revert this change? I fixed this in [8df3f19e](https://github.com/gregstoll/gallery2/commit/8df3f19e) and [81a15336](https://github.com/gregstoll/gallery2/commit/81a15336).

2022-11-12 12:42 UTC, miceno commented on lib/tools/phpunit/CodeAuditTestCase.class
> +			$this->skip();
To be honest, I don't know the purpose of this code.

It looks like it is there to check if there is a SVN tree. As we are not using SVN any more, it might be we should "translate" it to a GIT path, but not quite sure about the purpose.

Anyway, I will comment it too.

2022-11-12 19:13 UTC, miceno commented on modules/core/classes/GalleryUtilities.class
> -	    $value = (!is_null($value)) ? str_replace(array('&', '"', '<', '>'),
I had to refactor it a bit to keep test passing, but I think my proposed change is also a valid one. Please, let me know what you think about it.

2022-11-12 19:47 UTC, gregstoll commented on modules/core/classes/GalleryUtilities.class
> -	    $value = (!is_null($value)) ? str_replace(array('&', '"', '<', '>'),
Yeah, that should work too. Thanks!

2022-11-12 19:48 UTC, gregstoll approved these changes

2022-11-12 19:48 UTC, merged